# Generated by Django 4.0.2 on 2022-02-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggydoor', '0002_auto_20220203_1208'),
        ('doggydoor', '0003_auto_20220203_1816'),
    ]

    operations = [
    ]
